// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    Form: typeof import('./src/components/form.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconSearch: typeof import('@arco-design/web-vue/es/icon')['IconSearch']
    List: typeof import('./src/components/list.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Report: typeof import('./src/components/report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
